baseURL = 'https://samuel-allen.com/'
languageCode = 'en-us'
title = 'Samuel Allen'

cleanDestinationDir = true
enableGitInfo = true
enableRobotsTXT = true

publishDate = ['publishdate', 'pubdate', 'published', 'date']
lastmod = ['lastmod', ':fileModTime', ':git', 'modified', 'date', 'publishdate', 'pubdate', 'published']

[menus]
  [[menus.main]]
    name = 'dispatches'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'cv'
    pageRef = '/cv'
    weight = 20
  [[menus.main]]
    name = 'about'
    pageRef = '/about'
    weight = 30

