baseURL = 'https://samuel-allen.com/'
languageCode = 'en-us'
paginate = 10000
title = 'Samuel deHuszar Allen'
theme = "blank"

[permalinks]
  posts = '/:year/:month/:title/'
  skill = '/about/cv/skills/:slug'

[taxonomies]
  category = 'categories' 
  skill = 'skills'
  tag = 'tags'

[outputs]
  home = ['HTML', 'JSON', 'RSS']
  page = ['HTML']
  section = ['HTML', 'JSON', 'RSS']
  taxonomy = ['HTML', 'JSON', 'RSS']
  term = ['HTML', 'JSON', 'RSS']

